UserSettings/UserSettings.cpp, UserSettings/UserSettings.h, UserSettings/UserSettingsImplementation.cpp, UserSettings/UserSettingsImplementation.h
Reason for change: Added user settings inspector interface to user settings plugin.
Test Procedure: Make full stack build and verify user settings inspector interface.
https://etwiki.sys.comcast.net/display/RDKV/User+Settings+Inspector
Risks: Low
Priority: P1
=> RDK-56276: Add user settings inspector interface to user settings plugin

CMakeLists.txt, StorageManager/CHANGELOG.md, StorageManager/CMakeLists.txt, StorageManager/Module.cpp, StorageManager/Module.h, StorageManager/README.md, StorageManager/StorageManager.conf.in, StorageManager/StorageManager.config, StorageManager/StorageManager.cpp, StorageManager/StorageManager.h, StorageManager/StorageManagerImplementation.cpp, StorageManager/StorageManagerImplementation.h
Reason for change: Add initial implementation for Storage Manager
Test Procedure: Plugin activation and de-activation
Risks: Low
Priority: P1
Signed-off-by: Sourav Dutta bp-sdutta290@cable.comcast.com
=> RDKEMW-2056: Add initial implementation for storagemanager

StorageManager/StorageManagerImplementation.cpp, StorageManager/StorageManagerImplementation.h
Reason for change : Implementation of GetStorage Method
Test Procedure: Tested GetStorage functionality successfully
Risks: Medium
Priority: P1
=> RDKEMW-2021 : Implemented GetStorage API

StorageManager/StorageManagerImplementation.cpp, StorageManager/StorageManagerImplementation.h
Reason for change: Implementation of clear and clearAll methods
Test Procedure: Tested clear and clearAll  functionality successfully
Risks: Medium
Priority: P1
Signed-off-by: Pavithra V bp-pviswa149@cable.comcast.com
=> RDKEMW-2022: Implementation of clear and clearAll

LifecycleManager/ApplicationContext.cpp, LifecycleManager/LifecycleManagerImplementation.cpp, LifecycleManager/RippleHandler.cpp, LifecycleManager/State.cpp, LifecycleManager/WebSocket.cpp
Reason for change: 16 coverity issues reported in ubuntu coverity scan Test Procedure: verify LCM functionality for regressions. Risks: Low
Priority:P3
Signed-off-by: sajilal711 <shreyas.sajilal@gmail.com>
=> RDKEMW-1667: Fix coverity scan issues of LifecycleManager

StorageManager/StorageManagerImplementation.cpp, StorageManager/StorageManagerImplementation.h
Reason for change : implement deleteStorage
Test Procedure: Tested deleteStorage functionality
Risks: Medium
Priority: P1
Signed-off-by: Dali Hariharan bp-dharih957@cable.comcast.com
=> RDKEMW-2023 Implementation of deleteStorage

NativeJS/NativeJSImplementation.cpp, NativeJS/NativeJSPlugin.cpp
Reason for change: Cleaned up the code
Test Procedure: build should be successful.
Risks: low
Priority: P2
=> RDKEMW-2645 : NativeJS Plugin cleanup

AppManager/AppManagerImplementation.cpp, AppManager/AppManagerImplementation.h, AppManager/LifecycleInterfaceConnector.cpp, AppManager/LifecycleInterfaceConnector.h
Reason for change: AppMan -> PacMan lock and unlock support
Test Procedure: Validation of getting unpackedPath ,version and lockId 
Risks: Low
Priority: P0
Signed-off-by: Madhumathi R <bp-mbhand796@cable.comcast.com>
=> RDKEMW-1883 : AppManager lock and unlock call

PackageManager/PackageManagerImplementation.cpp, helpers/UtilsLogging.h
Reason for change : Fixing compilation issues
Test Procedure: 1. Package manager compilation is succesfull
2. libpackage is getting linked with package manager
Risks: Medium
Priority: P2
Signed-off-by: Abhay Kant bp-akant305@cable.comcast.com
=> RDKEMW-1741 : Integrating libPackage with package manager

RuntimeManager/RuntimeManagerImplementation.cpp, StorageManager/StorageManagerImplementation.cpp, StorageManager/StorageManagerImplementation.h
Reason for change : Parameter(userId, groupId) changes for CreateStorage and GetStorage API
Test Procedure: CreateStorage and GetStorage API response is OK
Risks: Medium
Priority: P1
Signed-off-by: Abhay Kant bp-akant305@cable.comcast.com
=> RDKEMW-1947 : Integrate Storage Manager with Package and Runtime Manager

OCIContainer/DobbyInterface.cpp, OCIContainer/DobbyInterface.h, OCIContainer/OCIContainerImplementation.cpp
Reason for change : Add Support for OCIContainer Notifications for Dobby Events
Test Procedure: Verfied the OCIContainer Notifications through logs
Risks: Medium
Priority: P1
=> RDKEMW-1599 : OCIContainer Notifications

.github/workflows/L1-tests.yml, .github/workflows/L2-tests.yml
Reason for change: [OSCR SCAN] RDKE - entservices-testframework
Test Procedure: NA
Risks: None
Priority: P2
Signed-off-by: bp-ppriya193@cable.comcast.com
=> RDKEMW-3207 [OSCR SCAN] RDKE - entservices-testframework

PackageManager/PackageManagerImplementation.cpp, helpers/UtilsLogging.h
Reason for change : Fix compilation issue for latest entservices-infra in packagemanager
Test Procedure: Package manager compilation is succesfull
Risks: Medium
Priority: P1
Signed-off-by: Abhay Kant bp-akant305@cable.comcast.com
=> RDKEMW-3818 : Fix compilation issue for latest entservices-infra

StorageManager/StorageManagerImplementation.cpp, StorageManager/StorageManagerImplementation.h
Reason for change : update Storage manager cache after reboot
Test Procedure: Tested storage manager
Risks: Medium
Priority: P2
Signed-off-by: Dali Hariharan bp-dharih957@cable.comcast.com
=> RDKEMW-2636 update Storage manager cache after reboot

PackageManager/PackageManagerImplementation.cpp
* return unpackedPath in Lock() even in already locked app
* Add configMetadata to Install() & Lock()
* fix unused variable error
=> RDKEMW-2577: LibPackage Abstraction for Entos (#120)

LifecycleManager/WindowManagerHandler.cpp, RuntimeManager/CMakeLists.txt, RuntimeManager/RuntimeManagerImplementation.cpp, RuntimeManager/RuntimeManagerImplementation.h, RuntimeManager/WindowManagerConnector.cpp, RuntimeManager/WindowManagerConnector.h
Reason for change: move createDisplay from LM to RM Test Procedure: refer ticket.
Risks: Low
Priority:P1
=> RDKEMW-3044: [AI2.0][RM][LM] Add changes for creating display from runtime manager

build_dependencies.sh, cov_build.sh
Reason for change: Coverity integration with middleware component workflow 
Test Procedure: Verify checks in github
Risks: Low
Signed-off-by:AkshayKumar_Gampa <AkshayKumar_Gampa@comcast.com>
=> RDK-55373:[RDKServices] Coverity integration with middleware component workflow

NativeJS/NativeJSImplementation.cpp, NativeJS/NativeJSImplementation.h
Reason for change: Cleaned up the code
Test Procedure: build should be successful.
Risks: low
Priority: P2
=> RDKEMW-3925 : Updating the interface api's

LifecycleManager/LifecycleManagerImplementation.cpp, LifecycleManager/RuntimeManagerHandler.cpp, RuntimeManager/CMakeLists.txt, RuntimeManager/DobbyEventListener.cpp, RuntimeManager/DobbyEventListener.h, RuntimeManager/IEventHandler.h, RuntimeManager/RuntimeManagerImplementation.cpp, RuntimeManager/RuntimeManagerImplementation.h, RuntimeManager/WindowManagerConnector.cpp
Reason for change: wire up dobby event listeners in RuntimeManager 
Risks: Low
Priority:P1
=> RDKEMW-1668: [AI2.0][RM] Add Event handling implementation for Dobby event listeners

RuntimeManager/RuntimeManagerImplementation.cpp
Reason for change : IRuntimeManager.suspend and resume method
Test Procedure: NA
Risks: Low
Priority: P1
Signed-off-by: Siva Thandayuthapani [sithanda@synamedia.com](mailto:sithanda@synamedia.com)
=> RDKEMW-1386 RDKEMW-1387: IRuntimeManager.suspend and resume

.github/workflows/L1-tests.yml, Tests/L1Tests/CMakeLists.txt, Tests/L1Tests/tests/test_ResourceManager.cpp
Reason For Change: Adding Test case
Test procedure : Run L1tests.yml
Risks : Low
=> RDKEMW-3807 : L1 Test file for ResourceManager plugin

.github/workflows/L1-tests.yml, Tests/L1Tests/CMakeLists.txt, Tests/L1Tests/tests/test_ResourceManager.cpp
Reason For Change: Adding Test case
Test procedure : Run L1tests.yml
Risks : Low
=> RDKEMW-3807 : L1 Test file for ResourceManager plugin (#220)

RuntimeManager/AIConfiguration.cpp, RuntimeManager/AIConfiguration.h
Reason for change: read AI Config Params from config.ini file 
Risks: Low
Priority:P1
=> RDKEMW-3811: [AI2.0][RM] Read system config parameters from ini file

Tests/L1Tests/tests/test_UserSettings.cpp, UserSettings/UserSettingsImplementation.cpp
Reason for change: Added new property content Pin in User settings
Test Procedure: Run curl commands on box and test the content Pin. refer below page.
https://etwiki.sys.comcast.net/pages/viewpage.action?spaceKey=RDKV&title=User+Settings
Risks: NO
Priority: P1
=> RDK-57747: The contentPin should match the requirement.

.github/workflows/L2-tests.yml
Resolve no such file directory issue on testframework repo while running L2-infra test
=> Update L2-tests.yml (#440)

.github/workflows/L2-tests.yml
Reason for Change: Added for CT
Test Procedure: Check for regressions
Risks: Low
Priority: P1
=> RDKEMW-6671 - Add patch Jsonrpc_dynamic_error_handling.patch

.github/workflows/L2-tests.yml
Reason for Change: Added for CT
Test Procedure: Check for regressions
Risks: Low
Priority: P1
=> RDKEMW-6671 - Add patch Jsonrpc_dynamic_error_handling.patch (#455)

CMakeLists.txt, TelemetryMetrics/CMakeLists.txt, TelemetryMetrics/Module.cpp, TelemetryMetrics/Module.h, TelemetryMetrics/TelemetryFilters.h, TelemetryMetrics/TelemetryMetrics.conf.in, TelemetryMetrics/TelemetryMetrics.config, TelemetryMetrics/TelemetryMetrics.cpp, TelemetryMetrics/TelemetryMetrics.h, TelemetryMetrics/TelemetryMetricsImplementation.cpp, TelemetryMetrics/TelemetryMetricsImplementation.h, helpers/TelemetryMetricsReporting.cpp, helpers/TelemetryMetricsReporting.h
Reason For change: Telemetry Plugin Implementation
Risks: Medium
Priority: P1
=> RDKEMW-2993 : Add Telemetry Plugin

CMakeLists.txt, DownloadManager/CMakeLists.txt, DownloadManager/DownloadManager.conf.in, DownloadManager/DownloadManager.config, DownloadManager/DownloadManager.cpp, DownloadManager/DownloadManager.h, DownloadManager/DownloadManagerHttpClient.cpp, DownloadManager/DownloadManagerHttpClient.h, DownloadManager/DownloadManagerImplementation.cpp, DownloadManager/DownloadManagerImplementation.h, DownloadManager/Module.cpp, DownloadManager/Module.h
Reason for change: New AI2.0 DownloadManager Plugin
Test Procedure: Build and testing have been verified in the full stack
Risks: Medium
Priority: P1
Signed-off-by: Arularasan Namachivayam [anamachi@synamedia.com](mailto:anamachi@synamedia.com)
=> RDKEMW-6752: AI2.0 DownloadManager plugin

.github/workflows/tests-trigger.yml, AppManager/AppManagerImplementation.cpp, AppManager/AppManagerImplementation.h, AppManager/LifecycleInterfaceConnector.cpp, LifecycleManager/LifecycleManagerImplementation.cpp, Tests/L1Tests/tests/test_AppManager.cpp, Tests/L2Tests/tests/AppManager_L2Test.cpp
Reason for change: Add type and lifecycleState to getLoadedApps response
Test Procedure: Build and testing have been verified in AI2.0, L1 and L2 workflow
Risks: Low
Priority: P1
Signed-off-by: Arularasan Namachivayam [anamachi@synamedia.com](mailto:anamachi@synamedia.com)
=> RDKEMW-7402_7403: [AI2.0]Add type and lifecycleState to getLoadedApps

AppManager/AppManagerImplementation.cpp, AppManager/AppManagerImplementation.h, Tests/L1Tests/tests/test_AppManager.cpp, Tests/L2Tests/tests/AppManager_L2Test.cpp
Reason for change: Add Error handling for launch and preload failure.
Risks: Low
Priority: P1
Signed-off-by: Sundara Raja Moorthy S [bp-ssubra878@cable.comcast.com](mailto:bp-ssubra878@cable.comcast.com)
=> RDKEMW-7853 :[AI2.0]Error codes for launch/preload

AppManager/AppManagerImplementation.cpp
Reason for change: Add Error handling for launch and preload failure.
Risks: Low
Priority: P1
Signed-off-by: Sundara Raja Moorthy S [bp-ssubra878@cable.comcast.com](mailto:bp-ssubra878@cable.comcast.com)
=> RDKEMW-7853 :[AI2.0] Fix the confict issue.

AppManager/AppManagerImplementation.cpp, AppManager/AppManagerImplementation.h, AppManager/LifecycleInterfaceConnector.cpp, AppManager/LifecycleInterfaceConnector.h, LifecycleManager/LifecycleManagerImplementation.cpp, LifecycleManager/LifecycleManagerImplementation.h, RuntimeManager/DobbySpecGenerator.cpp, RuntimeManager/RuntimeManagerImplementation.cpp, RuntimeManager/RuntimeManagerImplementation.h, Tests/L1Tests/tests/test_AppManager.cpp, Tests/L1Tests/tests/test_RunTimeManager.cpp, Tests/L2Tests/tests/AppManager_L2Test.cpp
Reason for change: Add check for wrong values.
Risks: Low
Priority: P1
Signed-off-by: Sundara Raja Moorthy S [bp-ssubra878@cable.comcast.com](mailto:bp-ssubra878@cable.comcast.com)
Note: Available PRS
RDKEMW-7851 - [AI2.0] Add check for wrong values
RDKEMW-7853 - [AI2.0][AM] Updates for launchApp/preloadapp
=> RDKEMW-7851 - [AI2.0] Add check for wrong values

RuntimeManager/AIConfiguration.cpp, RuntimeManager/AIConfiguration.h, RuntimeManager/CMakeLists.txt, RuntimeManager/RialtoConnector.cpp, RuntimeManager/RialtoConnector.h, RuntimeManager/RuntimeManagerImplementation.cpp, RuntimeManager/RuntimeManagerImplementation.h
When launching apps in container mode, initiate Rialto session based on window and app id , so that apps can play video using Rialto session.
=> RDKEMW-7279: Initiate Rialto session inside DAC app
