- RuntimeManager/ApplicationConfiguration.h
- RuntimeManager/RuntimeManagerImplementation.cpp
- RuntimeManager/RuntimeManagerImplementation.h
StorageManager use
Reason for change : Add appId as an argument to
run method
Test Procedure: Check if appId is stored in database if passed Risks: Low
Priority: P1
Signed-off-by: Pavithra V pavviswa@synamedia.com
> RDKEMW-2055: Add appId parameter to run api for

- USBDevice/USBDevice.cpp
- USBDevice/USBDevice.h
- USBMassStorage/USBMassStorage.cpp
**Reason for change:**
Activated/Deactivated debug messages from USB plugins are misleading. Plugin has a debug log that says that
Activated/Deactivated for plugin status first and checking whether it is for own plugin by checking the channel Id. So, debug is moved inside if condition, where we verified the incoming channel Id is matched with current plugin.
**Test Procedure:**
Create full stack build and verify logs disappeared.
**Risks:** High
**Priority:** P1
> RDKEMW-2203: Typo in callsign for UsbDevice

- AppManager/LifecycleInterfaceConnector.cpp
- AppManager/LifecycleInterfaceConnector.h
Reason for change : Ensure events received inside appmanager
Test Procedure: launchApp is not crashing
Risks: Medium
Priority: P1
Signed-off-by: Dali Hariharan bp-dharih957@cable.comcast.com
> RDKEMW-2359 Ensure events received inside appmanager

- RuntimeManager/ApplicationConfiguration.h
- RuntimeManager/RuntimeManagerImplementation.cpp
- RuntimeManager/RuntimeManagerImplementation.h
Reason for change: Call StorageManager.getStorage to retrieve and store app storage information in Runtime Manager.
Test Procedure: Validation of app storage information retrieval from run method
Risks: Low
Priority: P1
Signed-off-by: Sourav Dutta bp-sdutta290@cable.comcast.com
> RDKEMW-1948: Integrate Runtime manager with Storage Manager

- UserSettings/CHANGELOG.md
- UserSettings/UserSettings.cpp
- UserSettings/UserSettingsImplementation.cpp
- UserSettings/UserSettingsImplementation.h
Reason for change:
RDKEMW-2483: Out of range values are accepted by org.rdk.UserSettings.setVoiceGuidanceRate api.
RDK-56276: Updated version numbers and changelog.md and documentation
Test Procedure: Make full stack build and verify user settings setVoiceGuidanceRate api.
https://etwiki.sys.comcast.net/display/RDKV/User+Settings+Inspector
Risks: Low
Priority: P1
> RDKEMW-2483: Out of range values are accepted by org.rdk.UserSettings setVoiceGuidanceRate api.

- Telemetry/TelemetryImplementation.cpp
- Telemetry/TelemetryImplementation.h
- helpers/PluginInterfaceBuilder.h
- helpers/frontpanel.cpp
RDK-56621: Update all the power manager plugin clients to new register events
Reason for changes: The PowerManager plugin's events are separated into different classes
Test procedure: Full stack build
> RDK-56621: Update all the power manager plugin clients to new register events

- AppManager/LifecycleInterfaceConnector.cpp
Reason for change : Mapping appPath to package manager unpackedPath
Test Procedure: spawnApp response is OK and crun lists the new app launched
Risks: Medium
Priority: P1
Signed-off-by: Abhay Kant bp-akant305@cable.comcast.com
> RDKEMW-1884 : [Ai2] AppMan -> LifeMan spawnApp

- AppManager/LifecycleInterfaceConnector.cpp
Reason for change : PackageInfo gets reset if loadedAppInfo moved
Test Procedure: Called Preload and again called launch, packageManager is not locked twice
Risks: Medium
Priority: P1
> RDKEMW-2802 : Handling of check package during launch 

- Telemetry/TelemetryImplementation.cpp
- Telemetry/TelemetryImplementation.h
Reason for change: Interface API arguments should not be passed by reference if they are primitive data types.
Test Procedure: SetPowerState & QueryPowerState sanity
Risks: LOW
> RDK-57093: Update Plugin Clients to use update Power manager interface

- .github/workflows/L1-tests.yml
Reason for change: Fixing the OCIContainer L1 test.
Test Procedure: OCIContainer L1 test run.
Risks: Low
Priority: P2
Signed-off-by: Sourav Dutta bp-sdutta290@cable.comcast.com
> RDKEMW-2686: L1 - Fixing the OCIContainer test

- RuntimeManager/CMakeLists.txt
Reason for change : L1 test for RuntimeManager
Test Procedure: Run L1 test to verify
Risks: Medium
Priority: P2
Signed-off-by: Dali Hariharan bp-dharih957@cable.comcast.com
> RDKEMW-1531: L1 test for RuntimeManager

- AppManager/AppManagerImplementation.cpp
AppManager changes are committed in lifecycle2.0 branch.  I made a quick fix for the build issue.
> RDKEMW-4107: Missing additionalMetadata in IPackageImpl.Install

- LifecycleManager/LifecycleManagerImplementation.cpp
- LifecycleManager/State.cpp
Reason for change : Fixed lifecycle state change, Correction in SpawnApp getContext() paramter interchanged, remove SuspendedState sem_wait
Test Procedure: NA
Risks: Low
Priority: P1
Signed-off-by: Siva Thandayuthapani [sithanda@synamedia.com](mailto:sithanda@synamedia.com)
> RDKEMW-4311:[AI2.0][LM]  Changes required for target lifecycle state Active and suspended

- build_dependencies.sh
- cov_build.sh
Reason for change: Coverity integration with middleware component workflow 
Test Procedure: Verify checks in github
Risks: Low
Signed-off-by:AkshayKumar_Gampa <AkshayKumar_Gampa@comcast.com>
> RDKEMW-4138:Coverity integration with Entservices-infra repo

- build_dependencies.sh
- cov_build.sh
Reason for change: Coverity integration with middleware component workflow Test Procedure: Verify checks in github
Risks: Low
Signed-off-by:AkshayKumar_Gampa <AkshayKumar_Gampa@comcast.com>
> RDKEMW-4138:Coverity integration with Entservices-infra repo (#197)

- AppManager/AppManagerImplementation.cpp
- AppManager/AppManagerImplementation.h
- AppManager/LifecycleInterfaceConnector.cpp
- AppManager/LifecycleInterfaceConnector.h
Reason for change : Listens for onAppLifecycleStateChanged and onAppInstallationStatus
Test Procedure: Verified notification arises during state change/install/uninstall
Risks: Medium
Priority: P1
Signed-off-by: Pavithra V bp-pviswa149@cable.comcast.com
> RDKEMW-3886 : [AppManager] Events registration

- AppManager/AppManagerImplementation.cpp
- AppManager/AppManagerImplementation.h
- AppManager/LifecycleInterfaceConnector.cpp
- AppManager/LifecycleInterfaceConnector.h
Reason For change: Ensure proper state is set on launch
Support packageinstallation methods and events
Test Procedure: verified with json rpc curl command Risks: Medium Priority: P1
> RDKEMW-3885-4159: Launch state set with events

- AppManager/AppManagerImplementation.cpp
Reason For change: Fix to not lock during Suspend/Paused/Hibernate state
Test Procedure: verified with json rpc curl command Risks: Medium
Priority: P1
> RDKEMW-4159 : Fix to not lock during Suspend state

- Tests/L1Tests/tests/test_UserSettings.cpp
- Tests/L2Tests/tests/UserSettings_L2Test.cpp
- UserSettings/CHANGELOG.md
- UserSettings/UserSettings.cpp
- UserSettings/UserSettingsImplementation.cpp
Reason for change: Added L1 and L2 tests for new property content Pin in User settings.
Test Procedure: Run L1 and L2 test yml files and verify all test cases are passing.
Risks: NO
Priority: P1
> RDK-57747: Added L1 and L2 test cases for content pin property

- AppManager/LifecycleInterfaceConnector.cpp
- AppManager/LifecycleInterfaceConnector.h
- LifecycleManager/State.cpp
- PackageManager/PackageManagerImplementation.cpp
Reason for change : Setting proper states on deactivate/resume
Test Procedure: Verified using curl cmds
Risks: Medium
Priority: P1
Signed-off-by: Pavithra V bp-pviswa149@cable.comcast.com
> RDKEMW-3893: Ensure proper states are set

- AppManager/LifecycleInterfaceConnector.cpp
Reason For change: AppManager syncs cache via LifecycleManager's GetLoadedApps and reporting back to the application.
Test Procedure: Verified via Thunder RPC
Risks: Low
Priority: P1
Signed-off-by:Veeksha Gokul M S bp-vgokul492@cable.comcast.com
> RDKEMW-4589:update GetLoadedApps to get details from LM

- Tests/L2Tests/tests/UserSettings_L2Test.cpp
Reason for change: Commenting failure testcases
Test Procedure: NA
Risks: None
Priority: P2
Signed-off-by: bp-ppriya193@cable.comcast.com
> [RDKEMW-2711] RDKEMW-5315 L2 Usersettings Test case SetAndGetMethods failure

- .github/workflows/L2-tests.yml
- OCIContainer/CMakeLists.txt
- OCIContainer/DobbyInterface.h
- Tests/L2Tests/CMakeLists.txt
- Tests/L2Tests/tests/OCIContainer_L2Test.cpp
* RDK-55559 : Add L1 & L2 tests for OCIContainer plugin Reason for change: Adding L2 test cases for latest COM-RPC supported OCIContainer plugin.
Test Procedure: Run L2test to verify
Risks: Medium
* Update L2-tests.yml
* Update L2-tests.yml
* Update OCIContainer_L2Test.cpp
* Update L2-tests.yml
* Update OCIContainer_L2Test.cpp
* Update L2-tests.yml
* Update OCIContainer_L2Test.cpp
* Update L2-tests.yml
* Update the CMakeLists.txt to remove changes from the implementation
* Update L2-tests.yml
* Update L2-tests.yml
* Update L2-tests.yml
* Update L2-tests.yml
* Update L2-tests.yml
* Update OCIContainer_L2Test.cpp
---------
> RDK-55559 : Add L1 & L2 tests for OCIContainer plugin (#362)

- RDKShell/RDKShell.cpp
- RDKShell/RDKShell.h
When `RDKSHELL_FRAMERATE` is set to 60, the loop inside `shellThread` is locking the `gRdkShellMutex` more frequently, potentially leading to live-lock of injectKey handling. 
This manifests as an increased response time of injectKey API call, compared to `RDKSHELL_FRAMERATE=30`, which can reach several seconds.
> RDKEMW-5966: Handle injectKey requests in task queue to reduce latency

- PersistentStore/sqlite/Store2.h
Reason for change: initialize sqlite handle with nullptr to mute coverity report.
Test Procedure: None
Risks: None
> RDKEMW-7050 : fix coverity issues (#479)

- Tests/L1Tests/tests/test_AppManager.cpp
Reason For change: Fix for L1 intermittent failure 
Risks: Medium
Priority: P1
Signed-off-by: Madhumathi R [bp-mbhand796@cable.comcast.com](mailto:bp-mbhand796@cable.comcast.com)
> RDKEMW-8472: Appmanager L1 - update the test to fix intermittent failure  
